### ISSUE TITLE
"Error in 'src/trainers/reconstruct.py': 'image_meta_dict' Missing in Batch"

### ISSUE THREAD

**Issue by Seokho23** [marksgraham/ddpm-ood#8]
Thank you for your great research. However, I am having some difficulty with code reproduction. In the file '/ddpm-ood/src/trainers/reconstruct.py', at line 194, the code filename = batch["image_meta_dict"]["filename_or_obj"][b] produces an error stating that "image_meta_dict" does not exist in the batch.

I have tried debugging, but since the Dataset used in ddpm-ood is based on monai, it's challenging to pinpoint exactly where the error is occurring. Are there any issues when conducting experiments with MNIST and FashionMNIST?

I would appreciate any solution you could provide for this problem.

![image](https://github.com/marksgraham/ddpm-ood/assets/89764044/c2b50627-2fa8-41cd-92e2-597ccdb17999)
![image](https://github.com/marksgraham/ddpm-ood/assets/89764044/9a01752a-a918-4048-a296-2cc992ead9fb)

**Comment by marksgraham** [comment]
hi there,

can you print what keys batch has, e.g. `batch.keys()`?

**Comment by Seokho23** [comment]
Thank you for your prompt response.

The result of `batch.keys()` is observed to contain only **'image'**, as depicted in the image below. This observation was made during an experiment where FashionMNIST was used for in-distribution training, followed by setting MNIST as the out-of-distribution dataset.

Given this setup, I would expect batch.keys() to reflect more than just 'image', but that doesn't seem to be the case. Could there be an underlying issue with the dataset processing or loading mechanisms?

![image](https://github.com/marksgraham/ddpm-ood/assets/89764044/d56171b3-0e00-42ba-8bf3-a1e075b4f94a)

**Comment by marksgraham** [comment]
What version of MONAI are you using? And have you made any changes to the codebase?

**Comment by Seokho23** [comment]
The versions of monai and monai-generative are as follows:
> monai                     1.3.0
> monai-generative          0.2.2

**Comment by marksgraham** [comment]
I trained with MONAI 1.2.0, it could be work downgrading and seeing if that helps but I would be surprised if it did. 

If that doesn't work then it is hard to identify the problem but there is a fairly easy solution. The bug is just caused by it failing to find the filename for saving results, but you don't really need the filename, just a unique identifier for each image. 

so you could replace the failing line with something like

``` 
for b in range(images.shape[0]):
    filename = ctr + b
    stem = filename
```

and make sure you initalise with `ctr=0` before the whole loop and add `ctr+= images.shape[0]` once you're finished with that batch

**Comment by Seokho23** [comment]
After changing the version to MONAI 1.2.0 and running the code, the problem was resolved. I really appreciate your help.

**Comment by marksgraham** [comment]
Good to know! I've pinned MONAI to 1.2.0 in requirements.txt so this doesn't happen again
